/*
 * Copyright 2026 ValeEng
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Implementation of spody_convert_icgem_to_tab. See spody_icgem.h for
 * the format references (Barthelmes & Foerste 2011 for ICGEM; Pavlis et
 * al. 2012 for EGM2008) and the contract.
 *
 * Memory: a full N=2190 Earth model has (N+1)(N+2)/2 ~ 2.4 M triangular
 * entries; we allocate 4 dense arrays (C, S, sigma_C, sigma_S) for a
 * worst-case ~75 MB working set. Trivial on any host that can also load
 * the file at runtime, and avoids requiring the .gfc to be sorted by
 * (l, m) (the spec doesn't mandate sort order; EGM2008 happens to be
 * sorted but EIGEN-* sometimes isn't).
 *
 * Output layout: mirrors data/GRGM1200B/gggrx_1200b_sha.tab byte-for-
 * byte in structure so the existing loader needs no change. Field 1 =
 * R_ref (km), field 2 = GM (km^3/s^2), field 3 = sigma_GM (km^3/s^2),
 * field 4 = max_degree, field 5 = same again, field 6 = 1, fields 7-8
 * = 0. Data rows start at n=1 with (1,0) and (1,1) padded to zero,
 * matching the GRAIL/PGDA convention.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "spody_icgem.h"

/* Line buffer. ICGEM body rows can carry l, m, C, S, sigma_C, sigma_S
 * plus an optional trailing comment; 1024 covers anything seen in the
 * wild. Header lines are always short. */
#define SPODY_ICGEM_BUF 1024

/* Body-row keyword. The header section ends at "end_of_head"; from
 * there on, only "gfc" rows are coefficients we care about. Other
 * keywords (gfct, dot, trnd, asin, acos) describe time-variable
 * gravity and are skipped with a count for the operator. */
#define SPODY_ICGEM_KEY_STATIC      "gfc"
#define SPODY_ICGEM_KEY_END_HEAD    "end_of_head"

/* Triangular index used by spody_load_HarmonicGravityData (see
 * spody_harmonics.c:88): idx(n,m) = n*(n+1)/2 + m. We mirror that
 * exactly so the on-disk byte layout matches what the loader will
 * later re-derive at read time. */
static inline size_t _tri_index(int n, int m) {
    return (size_t)n * (size_t)(n + 1) / 2u + (size_t)m;
}

/* Some legacy ICGEM files (especially those generated by Fortran tools)
 * still write exponents as "1.23D-04" instead of the ISO C "1.23E-04".
 * strtod doesn't recognise the D form. We swap in place over a copy so
 * the original string remains untouched for diagnostic prints. */
static double _parse_icgem_double(const char *token) {
    char buf[64];
    size_t i = 0;
    for (; token[i] && i < sizeof(buf) - 1; ++i) {
        char c = token[i];
        if (c == 'D' || c == 'd') c = 'E';
        buf[i] = c;
    }
    buf[i] = '\0';
    return strtod(buf, NULL);
}

/* In-place tokeniser: returns the next whitespace-delimited token in
 * *cursor*, advances *cursor* past it. NULL when the string is exhausted.
 * Lighter than strtok and reentrant (no static buffer). */
static char *_next_token(char **cursor) {
    char *p = *cursor;
    while (*p && isspace((unsigned char)*p)) ++p;
    if (!*p) { *cursor = p; return NULL; }
    char *start = p;
    while (*p && !isspace((unsigned char)*p)) ++p;
    if (*p) { *p = '\0'; ++p; }
    *cursor = p;
    return start;
}

/* Lower-case a buffer in place (ASCII). ICGEM keys are case-sensitive
 * per spec but several public files use mixed case (Modelname vs
 * modelname); fold so the comparisons below stay simple. */
static void _ascii_lowercase(char *s) {
    for (; *s; ++s) *s = (char)tolower((unsigned char)*s);
}

int spody_convert_icgem_to_tab(const char *input_gfc,
                               const char *output_tab,
                               int max_degree) {
    if (!input_gfc || !output_tab) {
        fprintf(stderr, "icgem: NULL input or output path\n");
        return 1;
    }

    FILE *fin = fopen(input_gfc, "r");
    if (!fin) {
        fprintf(stderr, "icgem: cannot open input '%s'\n", input_gfc);
        return 1;
    }

    /* --- Header pass ---------------------------------------------- */
    /* We read until "end_of_head", capturing the only header values
     * the loader needs (GM, radius, max_degree) plus operator-visible
     * metadata (model name, tide system, errors style). Unknown keys
     * are silently ignored: the format allows arbitrary additions. */
    char   model_name[64]   = "(unnamed)";
    char   tide_system[32]  = "(unspecified)";
    char   errors_style[32] = "no";
    double gm_m3s2          = 0.0;
    double radius_m         = 0.0;
    int    declared_max_deg = 0;
    int    in_body          = 0;

    char line[SPODY_ICGEM_BUF];
    while (fgets(line, sizeof(line), fin)) {
        char *cursor = line;
        char *key    = _next_token(&cursor);
        if (!key || key[0] == '#' || key[0] == '!') continue;
        char keylc[64];
        snprintf(keylc, sizeof(keylc), "%s", key);
        _ascii_lowercase(keylc);

        if (strcmp(keylc, SPODY_ICGEM_KEY_END_HEAD) == 0) {
            in_body = 1;
            break;
        }
        char *val = _next_token(&cursor);
        if (!val) continue;

        if (strcmp(keylc, "modelname") == 0) {
            snprintf(model_name, sizeof(model_name), "%s", val);
        } else if (strcmp(keylc, "earth_gravity_constant") == 0) {
            gm_m3s2 = _parse_icgem_double(val);
        } else if (strcmp(keylc, "radius") == 0) {
            radius_m = _parse_icgem_double(val);
        } else if (strcmp(keylc, "max_degree") == 0) {
            declared_max_deg = (int)strtol(val, NULL, 10);
        } else if (strcmp(keylc, "tide_system") == 0) {
            snprintf(tide_system, sizeof(tide_system), "%s", val);
        } else if (strcmp(keylc, "errors") == 0) {
            snprintf(errors_style, sizeof(errors_style), "%s", val);
        }
    }

    if (!in_body) {
        fprintf(stderr,
            "icgem: header has no 'end_of_head' marker in '%s'\n",
            input_gfc);
        fclose(fin);
        return 1;
    }
    if (gm_m3s2 <= 0.0 || radius_m <= 0.0 || declared_max_deg < 2) {
        fprintf(stderr,
            "icgem: header missing earth_gravity_constant, radius, "
            "or max_degree (got GM=%.6e, R=%.6e, N=%d)\n",
            gm_m3s2, radius_m, declared_max_deg);
        fclose(fin);
        return 1;
    }

    int output_N = (max_degree > 0 && max_degree < declared_max_deg)
                   ? max_degree : declared_max_deg;
    if (max_degree > declared_max_deg) {
        fprintf(stderr,
            "icgem: requested max_degree=%d exceeds file's declared "
            "max_degree=%d; truncating to %d.\n",
            max_degree, declared_max_deg, declared_max_deg);
    }

    /* --- Coefficient storage -------------------------------------- */
    /* Dense triangle indexed by _tri_index(n, m). We allocate up to
     * output_N (anything above is dropped at parse time, saving memory
     * when the user asks for a truncated convert). Calloc zeroes the
     * pad rows (n=0, n=1) so the writer can emit them as zero rows
     * without a separate check. */
    size_t tri_size = _tri_index(output_N, output_N) + 1;
    double *C    = (double *)calloc(tri_size, sizeof(double));
    double *S    = (double *)calloc(tri_size, sizeof(double));
    double *sC   = (double *)calloc(tri_size, sizeof(double));
    double *sS   = (double *)calloc(tri_size, sizeof(double));
    if (!C || !S || !sC || !sS) {
        fprintf(stderr,
            "icgem: out of memory allocating coefficient triangle "
            "(N=%d, %zu entries each)\n", output_N, tri_size);
        free(C); free(S); free(sC); free(sS);
        fclose(fin);
        return 1;
    }

    /* --- Body pass ------------------------------------------------ */
    size_t n_read           = 0;
    size_t n_above_n        = 0;  /* dropped because l > output_N */
    size_t n_time_variable  = 0;  /* gfct / dot / trnd / asin / acos */
    size_t n_unknown        = 0;  /* malformed or unrecognised */
    while (fgets(line, sizeof(line), fin)) {
        char *cursor = line;
        char *key    = _next_token(&cursor);
        if (!key) continue;
        char keylc[16];
        snprintf(keylc, sizeof(keylc), "%s", key);
        _ascii_lowercase(keylc);

        if (strcmp(keylc, SPODY_ICGEM_KEY_STATIC) != 0) {
            /* Time-variable rows live alongside the static ones in
             * modern files (EGM2020, GOCE-DIR, GRACE). Spody-core does
             * not model time-variable gravity yet, so we count and
             * skip them. */
            if (strcmp(keylc, "gfct") == 0 || strcmp(keylc, "dot")  == 0 ||
                strcmp(keylc, "trnd") == 0 || strcmp(keylc, "asin") == 0 ||
                strcmp(keylc, "acos") == 0) {
                ++n_time_variable;
            } else if (key[0] != '#' && key[0] != '!') {
                ++n_unknown;
            }
            continue;
        }

        char *t_l = _next_token(&cursor);
        char *t_m = _next_token(&cursor);
        char *t_C = _next_token(&cursor);
        char *t_S = _next_token(&cursor);
        if (!t_l || !t_m || !t_C || !t_S) { ++n_unknown; continue; }

        int l = (int)strtol(t_l, NULL, 10);
        int m = (int)strtol(t_m, NULL, 10);
        if (l < 0 || m < 0 || m > l) { ++n_unknown; continue; }
        if (l > output_N)            { ++n_above_n;  continue; }

        double cval  = _parse_icgem_double(t_C);
        double sval  = _parse_icgem_double(t_S);
        double scval = 0.0, ssval = 0.0;
        /* sigma_C / sigma_S only present when errors != "no". */
        char *t_sC = _next_token(&cursor);
        char *t_sS = _next_token(&cursor);
        if (t_sC && t_sS) {
            scval = _parse_icgem_double(t_sC);
            ssval = _parse_icgem_double(t_sS);
        }

        size_t idx = _tri_index(l, m);
        C[idx]  = cval;
        S[idx]  = sval;
        sC[idx] = scval;
        sS[idx] = ssval;
        ++n_read;
    }
    fclose(fin);

    /* Operator-visible summary. Goes to stderr so the converted file's
     * stdout (none here, but the convention is consistent with `spody
     * convert ephemeris`) is reserved for downstream tooling. */
    fprintf(stderr,
        "icgem: %s  GM=%.10e m^3/s^2  R=%.4f m  N_declared=%d  "
        "tide=%s  errors=%s\n",
        model_name, gm_m3s2, radius_m, declared_max_deg,
        tide_system, errors_style);
    fprintf(stderr,
        "icgem: parsed %zu static rows (truncation N=%d kept all l<=N; "
        "%zu dropped above, %zu time-variable skipped, %zu unknown)\n",
        n_read, output_N, n_above_n, n_time_variable, n_unknown);

    /* --- Write the .tab ------------------------------------------- */
    FILE *fout = fopen(output_tab, "w");
    if (!fout) {
        fprintf(stderr, "icgem: cannot open output '%s'\n", output_tab);
        free(C); free(S); free(sC); free(sS);
        return 1;
    }

    /* Header line in GRGM CSV layout. Conversions: m -> km (/1000),
     * m^3/s^2 -> km^3/s^2 (/1e9). sigma_GM is not present in ICGEM
     * headers; we leave it 0. Fields 5-8 are not consumed by the
     * loader but kept structurally identical to the GRGM template so a
     * line-by-line diff against another model still parses on the eye. */
    double R_km     = radius_m / 1000.0;
    double GM_km3s2 = gm_m3s2  / 1.0e9;
    fprintf(fout,
        "%22.16E,%22.16E,%22.16E,%5d,%5d,%4d,%22.16E,%22.16E\n",
        R_km, GM_km3s2, 0.0,
        output_N, output_N, 1, 0.0, 0.0);

    /* Data rows. n starts at 1: the loader's triangular index reserves
     * slots for (1,0) and (1,1) even though degree-1 terms vanish when
     * the origin is at the body's centre of mass. Padding them to zero
     * matches data/GRGM1200B/gggrx_1200b_sha.tab. */
    size_t rows_written = 0;
    for (int n = 1; n <= output_N; ++n) {
        for (int m = 0; m <= n; ++m) {
            size_t idx = _tri_index(n, m);
            fprintf(fout,
                "%5d,%4d,%22.16E,%22.16E,%22.16E,%22.16E\n",
                n, m, C[idx], S[idx], sC[idx], sS[idx]);
            ++rows_written;
        }
    }

    fclose(fout);
    free(C); free(S); free(sC); free(sS);
    fprintf(stderr,
        "icgem: wrote %zu rows to %s\n", rows_written, output_tab);
    return 0;
}
